use_frameworks!

platform :ios, '10.0'

target 'TLCorePod_Example' do
  pod 'TLCorePod', :path => '../'

  target 'TLCorePod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
